Magic317/urls.py
# from django.contrib import admin
import xadmin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include, re_path
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),  # xadmin
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 富文本编辑器
    # re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('blog/', include('blog.urls'), name='blog')  # 指向blog
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),  # blog首页
    path('category=<cname>', views.category, name='category'),  # blog分类
    path('ajax/search', views.search, name='search'),  # blog分类
    path('tag/<tname>', views.tag, name='tag'),  # blog标签
    path('entry/<eid>', views.entry, name='entry'),  #blog文章内容
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Bloguser(models.Model):
    uname = models.CharField(verbose_name='用户名称', max_length=16)
    uemail = models.EmailField(verbose_name='用户邮箱', blank=True, null=True)
    uphone = models.CharField(verbose_name='用户手机号', max_length=11)
    upassword = models.CharField(verbose_name='用户密码', max_length=16)
    uavatar = models.ImageField(verbose_name='用户头像', upload_to='avatar_images/%Y/%m%d', blank=True, null=True)
    join_datatime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)
    last_login_datatime = models.DateTimeField(verbose_name='最后登录时间', auto_now=True)

    class Meta:
        verbose_name = '博客用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.uname


class Category(models.Model):
    cname = models.CharField(verbose_name='分类名称', max_length=16)
    corder = models.IntegerField(verbose_name='分类排序', default=0)

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.cname


class Tag(models.Model):
    tname = models.CharField(verbose_name='标签名称', max_length=16)

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tname


class Article(models.Model):
    atitle = models.CharField(verbose_name='文章标题', max_length=32)
    acontent = RichTextUploadingField(verbose_name='文章内容', config_name='default')
    image = models.ImageField(verbose_name='文章图片', upload_to='article_images/%Y/%m%d', blank=True, null=True)
    acategory = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.CASCADE,)
    atag = models.ManyToManyField(Tag, verbose_name='文章标签', blank=True)
    auser = models.ForeignKey(Bloguser, verbose_name='文章作者', on_delete=models.CASCADE,)
    views = models.PositiveIntegerField(verbose_name='文章阅读量', default=0)
    add_datatime = models.DateTimeField(verbose_name='文章添加时间', auto_now_add=True)
    update_datatime = models.DateTimeField(verbose_name='文章更新时间', auto_now=True)

    class Meta:
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.atitle


class Link(models.Model):
    lname = models.CharField(verbose_name='链接名称', max_length=16)
    lurl = models.URLField(verbose_name='链接地址', max_length=128)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.lname

blog/views.py
from django.shortcuts import render
from .models import Bloguser, Category, Tag, Article, Link
from django.core.paginator import Paginator, EmptyPage


# Create your views here.


def global_param(request):
    category_list = Category.objects.all()

    return {
        'category_list': category_list,
    }


def index(request):
    article_list = Article.objects.all()
    paginator = Paginator(article_list, 6)

    page = request.GET.get('page', 1)
    article = paginator.page(page)
    context = {
        'article': article,
    }
    return render(request, 'blog/index.html', context)


# 分类页
def category(request, cname):
    category_article_list = Article.objects.filter(acategory__cname=cname).order_by('-add_datatime')
    paginator = Paginator(category_article_list, 6)

    page = request.GET.get('page', 1)
    category_article = paginator.page(page)

    context = {
        'category_article': category_article,
        'cname': cname,
    }
    return render(request, 'blog/category_list.html', context)


# 搜索
def search(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword', None)
        if keyword:
            result = Article.objects.filter(atitle__icontains=keyword)
            context = {
                'result': result,
            }
            return render(request, 'blog/serach_list.html', context)


def tag(request, tname):
    tag_article_list = Article.objects.filter(atag__tname=tname)
    # tag_name = Tag.objects.get(tname = tname)
    context = {
        'tag_article_list': tag_article_list,
        # 'tag_name': tag_name,
    }
    return render(request, 'blog/tag.html', context)


def entry(request, eid):
    entry = Article.objects.get(id=eid)
    previous_blog = Article.objects.filter(add_datatime__gt=entry.add_datatime).first()
    next_blog = Article.objects.filter(add_datatime__lt=entry.add_datatime).last()
    entry.views += 1
    entry.save()

    context = {
        'entry': entry,
        'previous_blog': previous_blog,
        'next_blog': next_blog,
    }
    return render(request, 'blog/entry.html', context)

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

blog/templates/blog/card.html
{% load static %}
<div class="mdl-grid">
    {% for article in article_list %}
        <div class="mdl-cell mdl-card mdl-shadow--4dp">
            <div class="mdl-card__media">
                <img class="article-image" src="{% static 'blog/images/gtx.jpg' %}" border="0" alt="">
            </div>
            <div class="mdl-card__title mdl-card--border">
                {{ article.atitle }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    person
                </div>
                作者：{{ article.auser }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    event
                </div>
                更新：{{ article.update_datatime }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{% url 'blog:entry' article.id %}">
                    阅读更多
                </a>
{#                <div class="mdl-layout-spacer"></div>#}
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect" >
                    <i class="material-icons">thumb_up</i>
                </a>
            </div>
        </div>
    {% endfor %}
</div>

blog/templates/blog/category.html
{% extends 'blog/index.html' %}
{% load static %}
{% block article_list %}
    {% for article in category_article_list %}
        <div class="mdl-cell mdl-card mdl-shadow--4dp">
            <div class="mdl-card__media">
                <img class="article-image" src="{% static 'blog/images/photo.jpg' %}" border="0" alt="">
            </div>
            <div class="mdl-card__title mdl-card--border">
                {{ article.atitle }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    person
                </div>
                作者：{{ article.auser }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    event
                </div>
                更新：{{ article.update_datatime }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent"
                   href="{% url 'blog:entry' article.id %}">
                    阅读更多
                </a>
                {#                <div class="mdl-layout-spacer"></div>#}
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect">
                    <i class="material-icons">thumb_up</i>
                </a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'blog/index.html' %}
{% load static %}
{% block article_list %}
    {% for article in category_article %}
        <div class="mdl-cell mdl-card mdl-shadow--4dp">
            <div class="mdl-card__media">
                <img class="article-image" src="{{ article.image.url }}" border="0" alt="">
            </div>
            <div class="mdl-card__title mdl-card--border">
                {{ article.atitle }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    person
                </div>
                作者：{{ article.auser }}
            </div>
            <div class="mdl-card__supporting-text">
                <div class="material-icons">
                    event
                </div>
                更新：{{ article.update_datatime }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent"
                   href="{% url 'blog:entry' article.id %}">
                    阅读更多
                </a>
                {#                <div class="mdl-layout-spacer"></div>#}
                <a class="mdl-button mdl-js-button mdl-js-ripple-effect">
                    <i class="material-icons">thumb_up</i>
                </a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block paginator %}
    {% if category_article.has_previous %}
        <a href="{% url 'blog:category' cname %}?page={{ category_article.previous_page_number }}"
           class="demo-nav__button mdl-color-text--pink-A200"
           id="previous">
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--blue-200 mdl-color-text--grey-200"
                    role="presentation">
                <div class="icon material-icons">arrow_back</div>
            </button>
        </a>
        <div class="mdl-tooltip" data-mdl-for="previous">
            上一页
        </div>
    {% endif %}
    <div class="section-spacer"></div>
    {% if category_article.has_next %}
        <a href="{% url 'blog:category' cname %}?page={{ category_article.next_page_number }}"
           class="demo-nav__button mdl-color-text--pink-A200"
           id="next">
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--blue-200 mdl-color-text--grey-200"
                    role="presentation">
                <div class="icon material-icons">arrow_forward</div>
            </button>
        </a>
        <div class="mdl-tooltip" data-mdl-for="next">
            下一页
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/drawer.html
<div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout-title">Magic317</span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="{% url 'blog:index' %}">首页</a>
        {% for category in category_list %}
            <a class="mdl-navigation__link" href="{% url 'blog:category' category.cname %}">{{ category.cname }}</a>
        {% endfor %}
    </nav>
</div>

blog/templates/blog/footer.html
<footer class="mdl-mini-footer">
    <div class="mdl-mini-footer__left-section">
        <div class="mdl-logo">© Magic博客</div>
    </div>
    <div class="mdl-mini-footer__right-section">
        <ul class="mdl-mini-footer__link-list mdl-color-text--grey-900">
{#            <li><a href="#">Help</a></li>#}
{#            <li><a href="#">Privacy & Terms</a></li>#}
        </ul>
    </div>
</footer>

blog/templates/blog/header.html
<header class="page-header mdl-layout__header mdl-layout__header--waterfall">
    <!-- Top row, always visible -->
    <div class="page-header-logo mdl-layout__header-row">
        <!-- Title -->
        <span class="mdl-layout-title">Magic317博客</span>
    </div>
    <!-- Bottom row, not visible on scroll -->
    <div class="page-header-nav mdl-layout__header-row mdl-layout--large-screen-only">
        <!-- Navigation -->
        <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
        <a class="mdl-navigation__link" href="{% url 'blog:index' %}">首页</a>
            {% for category in category_list %}
                <a class="mdl-navigation__link" href="{% url 'blog:category' category.cname %}">{{ category.cname }}</a>
            {% endfor %}
        </nav>
    </div>
</header>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'blog/index_style.css' %}">
{% endblock %}

{% block header %}
    {% include 'blog/header.html' %}
{% endblock %}

{% block drawer %}
    {% include 'blog/drawer.html' %}
{% endblock %}

{% block content %}
    <div class="page-content-max-width">
        <form action="#" method="get">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                    <i class="material-icons">search</i>
                </label>
                <div class="mdl-textfield__expandable-holder">
                    <input class="mdl-textfield__input" type="text" id="search">
                    <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
                </div>
            </div>
        </form>
        <div class="mdl-grid">
            {% block article_list %}
                {% for article in article %}
                    <div class="mdl-cell mdl-card mdl-shadow--4dp">
                        <div class="mdl-card__media">
                            <img class="article-image" src="{{ article.image.url }}" border="0" alt="">
                        </div>
                        <div class="mdl-card__title mdl-card--border">
                            {{ article.atitle }}
                        </div>
                        <div class="mdl-card__supporting-text">
                            <div class="material-icons">
                                person
                            </div>
                            作者：{{ article.auser }}
                        </div>
                        <div class="mdl-card__supporting-text">
                            <div class="material-icons">
                                event
                            </div>
                            更新：{{ article.update_datatime }}
                        </div>
                        <div class="mdl-card__actions mdl-card--border">
                            <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent"
                               href="{% url 'blog:entry' article.id %}">
                                阅读更多
                            </a>
                            {#                <div class="mdl-layout-spacer"></div>#}
                            <a class="mdl-button mdl-js-button mdl-js-ripple-effect">
                                <i class="material-icons">thumb_up</i>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
        <nav class="page-content-nav mdl-cell mdl-cell--12-col">
            {% block paginator %}
                {% if article.has_previous %}
                    <a href="{% url 'blog:index' %}?page={{ article.previous_page_number }}"
                       class="demo-nav__button mdl-color-text--pink-A200"
                       id="previous">
                        <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--blue-200 mdl-color-text--grey-200"
                                role="presentation">
                            <div class="icon material-icons">arrow_back</div>
                        </button>
                    </a>
                    <div class="mdl-tooltip" data-mdl-for="previous">
                        上一页
                    </div>
                {% endif %}
                <div class="section-spacer"></div>
                {% if article.has_next %}
                    <a href="{% url 'blog:index' %}?page={{ article.next_page_number }}"
                       class="demo-nav__button mdl-color-text--pink-A200"
                       id="next">
                        <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--blue-200 mdl-color-text--grey-200"
                                role="presentation">
                            <div class="icon material-icons">arrow_forward</div>
                        </button>
                    </a>
                    <div class="mdl-tooltip" data-mdl-for="next">
                        下一页
                    </div>
                {% endif %}
            {% endblock %}
        </nav>
    </div>
{% endblock %}

{% block footer %}
    {% include 'blog/footer.html' %}
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            {#搜索#}
            $("#search").bind('input propertychange', function () {
                var keyword = $(this).val();
                if (keyword == '') {
                    $.ajax({
                        url: '',
                        teyp: 'GET',
                        dataType: 'html',
                        success: function (data) {
                            var html = $(data).find(".mdl-grid").html();
                            $('.mdl-grid').empty();
                            $('.mdl-grid').html(html);
                            $('.page-content-nav').show()
                        }
                    });
                } else {
                    $.ajax({
                        url: 'ajax/search',
                        data: {
                            'keyword': keyword
                        },
                        teyp: 'GET',
                        dataType: 'html',
                        success: function (data) {
                            $('.mdl-grid').empty();
                            $('.mdl-grid').html(data);
                            $('.page-content-nav').hide();
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

blog/templates/blog/serach_list.html
{% for article in result %}
    <div class="mdl-cell mdl-card mdl-shadow--4dp">
        <div class="mdl-card__media">
            <img class="article-image" src="{{ article.image.url }}" border="0" alt="">
        </div>
        <div class="mdl-card__title mdl-card--border">
            {{ article.atitle }}
        </div>
        <div class="mdl-card__supporting-text">
            <div class="material-icons">
                person
            </div>
            作者：{{ article.auser }}
        </div>
        <div class="mdl-card__supporting-text">
            <div class="material-icons">
                event
            </div>
            更新：{{ article.update_datatime }}
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent"
               href="{% url 'blog:entry' article.id %}">
                阅读更多
            </a>
            {#                <div class="mdl-layout-spacer"></div>#}
            <a class="mdl-button mdl-js-button mdl-js-ripple-effect">
                <i class="material-icons">thumb_up</i>
            </a>
        </div>
    </div>
{% endfor %}